name = "cloudflare-worker-typescript"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2022-01-12"
mode = "development"
debug = true

[build]
command = "npm run build"

[build.upload]
format = "modules"
dir = "dist"
main = "index.mjs"

[miniflare]
durable_objects_persist = true

[durable_objects]
bindings = [{ name = "YourDurableObject", class_name = "YourDurableObject" }]

[[migrations]]
tag = "v0"
new_classes = ["YourDurableObject"]
